project_id = "nbugxtqfzmdocqsrzyda"

[functions.generate-image]
verify_jwt = false

[functions.generate-diagram]
verify_jwt = false

[functions.explain-diagram]
verify_jwt = false

[functions.code-to-diagram]
verify_jwt = false

[functions.diagram-to-code]
verify_jwt = false

[functions.index-board]
verify_jwt = false

[functions.search-boards]
verify_jwt = false
